import { getShapesForRegion } from "./mapData.js";
import { getStylePreset } from "./styles.js";
import { ParsedPrompt } from "./types.js";

function mulberry32(seed: number) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashString(input: string): number {
  let h = 1779033703 ^ input.length;
  for (let i = 0; i < input.length; i++) {
    h = Math.imul(h ^ input.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return (h >>> 0) || 1;
}

function clamp(value: number, min: number, max: number) {
  return Math.max(min, Math.min(max, value));
}

function hexToRgb(hex: string) {
  const normalized = hex.replace("#", "");
  const bigint = parseInt(normalized, 16);
  return {
    r: (bigint >> 16) & 255,
    g: (bigint >> 8) & 255,
    b: bigint & 255
  };
}

function rgbToHex(r: number, g: number, b: number) {
  return (
    "#" +
    [r, g, b]
      .map((v) => clamp(Math.round(v), 0, 255).toString(16).padStart(2, "0"))
      .join("")
  );
}

function tweakColor(hex: string, amount: number) {
  const { r, g, b } = hexToRgb(hex);
  return rgbToHex(r + amount, g + amount, b + amount);
}

function varyPolygon(points: string, rand: () => number, variation: number): string {
  const maxShift = 8 * variation;

  return points
    .split(" ")
    .map((pair) => {
      const [xStr, yStr] = pair.split(",");
      const x = Number(xStr);
      const y = Number(yStr);

      const nx = x + (rand() - 0.5) * maxShift;
      const ny = y + (rand() - 0.5) * maxShift;

      return `${nx.toFixed(1)},${ny.toFixed(1)}`;
    })
    .join(" ");
}

export function generateMapSvg(parsed: ParsedPrompt): string {
  const width = 1000;
  const height = 700;
  const preset = getStylePreset(parsed.style);
  const shapes = getShapesForRegion(parsed.region);

  const seed = hashString(parsed.originalPrompt);
  const rand = mulberry32(seed);

  const title =
    parsed.region === "world"
      ? "World Political Map"
      : `${parsed.region[0].toUpperCase()}${parsed.region.slice(1)} Political Map`;

  const polygons = shapes
    .map((shape, index) => {
      const baseColor = preset.palette[index % preset.palette.length];
      const brightnessShift = (rand() - 0.5) * 50 * parsed.colorfulness;
      const fill = tweakColor(baseColor, brightnessShift);
      const points = varyPolygon(shape.points, rand, parsed.variation);

      return `
        <polygon
          points="${points}"
          fill="${fill}"
          stroke="${preset.border}"
          stroke-width="2"
          stroke-linejoin="round"
        />
        ${
          parsed.labels
            ? `<text
                x="${shape.labelX}"
                y="${shape.labelY}"
                font-size="14"
                text-anchor="middle"
                fill="${preset.label}"
                font-family="Arial, sans-serif"
                font-weight="700"
              >${shape.name}</text>`
            : ""
        }
      `;
    })
    .join("\n");

  return `
  <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
    <rect width="100%" height="100%" fill="${preset.background}" />
    <text x="40" y="52" font-size="30" fill="${preset.label}" font-family="Arial, sans-serif" font-weight="700">
      ${title}
    </text>
    <text x="40" y="82" font-size="15" fill="${preset.label}" font-family="Arial, sans-serif" opacity="0.8">
      Generated by PoliteAI
    </text>
    <g>${polygons}</g>
  </svg>
  `;
}
